### ISSUE TITLE
vllm with LMCache offline inference crashes when prompts tokens sum very long

### ISSUE THREAD

**Issue by XbzOnGit** [LMCache/LMCache#137]
**Describe the bug**  
With LMCache + vllm offline inference, using generate API of LLM class in vllm, it crashes with an assertion error when the sum of token length of prompts exceeds max_position_embeddings of model.  
(Here it is 32768).  

And note that this problem does not occur with vllm(without LMCache).  
(Check Additional context section for this).  

**To Reproduce**  
All the files mentioned here are attached as a zip file here.  
[reproduce.zip](https://github.com/user-attachments/files/17255875/reproduce.zip)

1. Copy short_ffmpeg.txt into current directory.  
2. Copy bugrun.py into current directory.  
This script calls generate twice, one with sum of tokens just below max_position_embeddings, one with just above.  
3. Copy example.yaml into current directory.  
The one in examples/frontend should work.  
4. LMCACHE_CONFIG_FILE=example.yaml python3 bugrun.py  

**Expected behavior**  
It should at least be able to generate the outputs.  
But now it runs into an assertion error.  
**Loggings**  
After filtering:  
```
lower_prompts token number in total: 32331
Processed prompts: 100% 39/39 


First batch total Time: 8.137094298377633 seconds


upper_prompts token number in total: 33160
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/vllm/worker/model_runner_base.py", line 112, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/username/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 123, in new_execute_model
[rank0]:     model_input.async_callback()
[rank0]:   File "/root/miniconda3/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 910, in _process_model_outputs
[rank0]:     assert len(seq_group_metadata_list) == len(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: AssertionError
```

**Additional context**  
Note that, simply replacing  
```
from lmcache_vllm.vllm import LLM, SamplingParams
```  
with  
```
from vllm import LLM, SamplingParams
```
in bugrun.py and rename it into vllmrun.py.  
Then run with  
```
python3 vllmrun.py
```
It works well and generates BOTH prompts correctly.  
```
lower_prompts token number in total: 32331
Processed prompts: 100% 39/39 


First batch total Time: 7.923778206110001 seconds


upper_prompts token number in total: 33160
Processed prompts: 100% 40/40 


Second batch total Time: 9.035210307687521 seconds
```

**Comment by XbzOnGit** [comment]
Sorry, this has been fixed with this [PR](https://github.com/LMCache/lmcache-vllm/pull/15) hours ago. Closing this issue.
