### ISSUE TITLE
[User questions] How LMCache identifies KV cache of chunk tokens?

### ISSUE THREAD

**Issue by dequeueing** [LMCache/LMCache#167]
Hi. I have some questions unsolved after reading the source code:

- In the RAG use case(demo3), how LMCache identifies the KV of each context texts, which is prepended with the user prompt?
- After the KV states of each context is retrieved, how are they blended(as described in the paper) and adjust their positional info? I could not find the codes related to it.

Thank you if you could show me the codes addressing issues mentioned above. ❤️

**Comment by qyy2003** [comment]
Are you referring to the CacheBlend paper? If that's the case, you should wait for pull #121 to be merged.

**Comment by ApostaC** [comment]
Hi Taojie @dequeueing  , thanks for the question!

For the first question, LMCache identifies the KV by the tokens of the text chunks. 

For the second question, the code is in PR #121 , and the key function is `CacheBlendImpl.blend` (https://github.com/ApostaC/LMCache/blob/3b10598303ccf6da37073504719773dd4addc8d1/lmcache/blend/executor.py#L76)

Please let us know if there are any other questions.

**Comment by dequeueing** [comment]
> Hi Taojie @dequeueing , thanks for the question!
> 
> For the first question, LMCache identifies the KV by the tokens of the text chunks.
> 
> For the second question, the code is in PR #121 , and the key function is `CacheBlendImpl.blend` (https://github.com/ApostaC/LMCache/blob/3b10598303ccf6da37073504719773dd4addc8d1/lmcache/blend/executor.py#L76)
> 
> Please let us know if there are any other questions.

Thanks for the response. 
I notice that in [demo3(the RAG demo)](https://github.com/LMCache/demo/tree/master/demo3-KV-blending), when fed to LLM, the text chunks are seperated by a seperator if optimization is on. 

 
```python
session.separator = " # # " if optimization else ""
``` 
```python
 def set_context(self, context_list):
        input_prompt = ""
        for context in context_list:
            input_prompt +=(self.separator + context)
        self.final_context = input_prompt
        self.messages.append({"role":"user", "content":input_prompt})
``` 

I guess that when processing the prompt each chunk will be extracted because of the seperator, but I could not find the corresponding code. Could you show me pls?

**Comment by ApostaC** [comment]
Hey, @dequeueing ! Sorry, I somehow missed the notification of your previous question. 
The corresponding code is here: https://github.com/LMCache/LMCache/blob/a15c89c20d2e0bd2fd68bbce5f04c797171643d3/lmcache/blend/retriever.py#L217

Btw, CacheBlend logic has already been merged. Feel free to try the blending example in the `examples/` folder.

**Comment by dequeueing** [comment]
> Hey, @dequeueing ! Sorry, I somehow missed the notification of your previous question. The corresponding code is here:
> 
> https://github.com/LMCache/LMCache/blob/a15c89c20d2e0bd2fd68bbce5f04c797171643d3/lmcache/blend/retriever.py#L217
> 
> Btw, CacheBlend logic has already been merged. Feel free to try the blending example in the `examples/` folder.

Thanks very much for the reply! I have a question about the `RetrieveStatus`:

```python
class RetrieveStatus(Enum):
    PREFILL = 1
    CHUNK_PREFILL = 2 # not last chunk
    CHUNK_PREFILL_LAST = 3
    NONE = 4
```

Could you please explain when the status would be returned as `CHUNK_PREFILL` ?

I tried precompute a single chunk, and feed the same chunk back to LLM again. And it prints that the returned status from `lmcache_should_retrieve` is `PREFILL ` instead of `CHUNK_PREFILL`.

```python
 # vllm_injection.py
 # LMCache retrieval
    retrieve_status = lmcache_should_retrieve(model_input, kv_caches)
```

I am a bit confused about this. Since the chunk given to LLM is exactly the same as the one that was pre-computed, shouldn't we skip prefill at all?

For example, If I change the `blend_kv.py` as follows:

```python
context_files = ["chunk1.txt"]
```

```python
user_prompt = [chunks[0]]
```

I think in this case we should entirely skip prefill.

Thanks in advance!

**Comment by ApostaC** [comment]
Hey, @dequeueing , `CHUNK_PREFILL` is for the "chunked prefill" feature when running vLLM. It's not related to the "chunks" in KV blending.

And if the chunk is exactly the same, it should skip all the prefill

**Comment by darren-qiu** [comment]
Hey，  @ApostaC，In the first step of executing demo3, when preprocessing the text chunk, the following error will occur? Please tell me how to solve it?

The first step is to execute according to the following script：
```
sudo docker run --runtime nvidia --gpus '"device=0"' \
    -v ${LOCAL_HF_HOME}:/root/.cache/huggingface \
    -v `pwd`/data:/input \
    -v `pwd`/data:/data \
    --env "HF_TOKEN=${HF_TOKEN}" \
    --ipc=host \
    --network=host \
    --entrypoint python3 \
    apostacyh/vllm:lmcache-blend \
    /lmcache/demo/precompute.py \
    --model ${MODEL} --lmcache-config-file /lmcache/demo/example.yaml --data-path /input \
```

The error that occurs is as follows：
```
Traceback (most recent call last):
  File "/lmcache/demo/precompute.py", line 44, in <module>
    llm = LLM(model=model_name, gpu_memory_utilization=0.5,
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 118, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 277, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 160, in __init__
    self._initialize_kv_caches()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 236, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 111, in determine_num_available_blocks
    return self.driver_worker.determine_num_available_blocks()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 153, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1036, in profile_run
    self.execute_model(seqs, kv_caches)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 925, in execute_model
    hidden_states = model_executable(**execute_model_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 315, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 252, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 205, in forward
    hidden_states = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 151, in forward
    attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Attention.forward() missing 3 required positional arguments: 'status', 'cache_fuse_metadata', and 'old_kv'
```

**Comment by darren-qiu** [comment]
> Hey， @ApostaC，In the first step of executing demo3, when preprocessing the text chunk, the following error will occur? Please tell me how to solve it?
> 
> The first step is to execute according to the following script：
> 
> ```
> sudo docker run --runtime nvidia --gpus '"device=0"' \
>     -v ${LOCAL_HF_HOME}:/root/.cache/huggingface \
>     -v `pwd`/data:/input \
>     -v `pwd`/data:/data \
>     --env "HF_TOKEN=${HF_TOKEN}" \
>     --ipc=host \
>     --network=host \
>     --entrypoint python3 \
>     apostacyh/vllm:lmcache-blend \
>     /lmcache/demo/precompute.py \
>     --model ${MODEL} --lmcache-config-file /lmcache/demo/example.yaml --data-path /input \
> ```
> 
> The error that occurs is as follows：
> 
> ```
> Traceback (most recent call last):
>   File "/lmcache/demo/precompute.py", line 44, in <module>
>     llm = LLM(model=model_name, gpu_memory_utilization=0.5,
>   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 118, in __init__
>     self.llm_engine = LLMEngine.from_engine_args(
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 277, in from_engine_args
>     engine = cls(
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 160, in __init__
>     self._initialize_kv_caches()
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 236, in _initialize_kv_caches
>     self.model_executor.determine_num_available_blocks())
>   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 111, in determine_num_available_blocks
>     return self.driver_worker.determine_num_available_blocks()
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 153, in determine_num_available_blocks
>     self.model_runner.profile_run()
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1036, in profile_run
>     self.execute_model(seqs, kv_caches)
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 925, in execute_model
>     hidden_states = model_executable(**execute_model_kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 315, in forward
>     hidden_states = self.model(input_ids, positions, kv_caches,
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 252, in forward
>     hidden_states, residual = layer(
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 205, in forward
>     hidden_states = self.self_attn(
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen2.py", line 151, in forward
>     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
> TypeError: Attention.forward() missing 3 required positional arguments: 'status', 'cache_fuse_metadata', and 'old_kv'
> ```

Hey，@ ApostaC
I also want to ask, Which version of the code does this image `apostacyh/vllm:lmcache-blend` use? Can you explain in detail the process of making the image, so that we can debug the problem ourselves?

**Comment by ApostaC** [comment]
Hey @darren-qiu , thanks for your interest to the LMCache project. The `apostacyh/vllm:lmcache-blend` uses a very old version of the code.
Our suggestion is you can install the latest dev branch of [LMCache](https://github.com/LMCache/LMCache) and [lmcache-vllm](https://github.com/LMCache/lmcache-vllm) using pip If you want to try the blending feature. There is an example under the `LMCache/examples/blend_kv` folder.

**Comment by darren-qiu** [comment]
Thank you @ApostaC 
There is a new question: If I want to implement `pre_compute` online, what should I do? 
Because if it calls `openai.chat` directly, a lot of extra data will be added, such as:
`prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n你会做什么呀？<|im_end|>\n<|im_start|>assistant\n'`

**Comment by ApostaC** [comment]
Hey, @darren-qiu, towards your question: 

> There is a new question: If I want to implement pre_compute online, what should I do?

Another team member, @XbzOnGit , has been working on this recently. 

Hey @XbzOnGit , is there any update about supporting blending for the online chat?

**Comment by XbzOnGit** [comment]
Hi, @darren-qiu, you can try the following code.
```
class KVPreCompute:

    def __init__(self, openai_api_key, openai_api_base):
        self.client = OpenAI(
            # defaults to os.environ.get("OPENAI_API_KEY")
            api_key=openai_api_key,
            base_url=openai_api_base,
        )
        self.model = self.client.models.list().data[0].id

    def precompute_kv(self, text_chunk):
        completion = self.client.completions.create(
            prompt=text_chunk,
            model=self.model,
            max_tokens=1,
        )
        return completion.choices[0].text
```

**Comment by darren-qiu** [comment]
Thanks, @XbzOnGit and @ApostaC 

I tested blend kv and found that the program did not take advantage of the kv that was preprocessed in advance. 

After that, I tried running the blend_kv example again and found that it had no effect (like #235 mentioned here). I didn’t change any code, but only modification was that the model was changed to Qwen2.5 (the modification method is as follows, #241). I don’t know if it has any impact.  

Could you please help confirm the cause of the problem? Thanks

**Comment by darren-qiu** [comment]
```
INFO LMCache: Initializing lmcache_vllm version 0.6.2.2, supporting vllm versions: ['0.6.1.post2', '0.6.1.dev238+ge2c6e0a82'] [2024-12-09 11:20:25,926] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/__init__.py:35
INFO LMCache: Loading LMCache config file example_blending.yaml [2024-12-09 11:20:25,982] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:135
INFO 12-09 11:20:26 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='/disk2/adam/zhigpt', speculative_config=None, tokenizer='/disk2/adam/zhigpt', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/disk2/adam/zhigpt, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
INFO 12-09 11:20:27 model_runner.py:1014] Starting to load model /disk2/adam/zhigpt...
Loading safetensors checkpoint shards:   0% Completed | 0/9 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  11% Completed | 1/9 [00:00<00:01,  4.57it/s]
Loading safetensors checkpoint shards:  22% Completed | 2/9 [00:00<00:01,  3.98it/s]
Loading safetensors checkpoint shards:  33% Completed | 3/9 [00:00<00:01,  4.71it/s]
Loading safetensors checkpoint shards:  44% Completed | 4/9 [00:00<00:01,  4.68it/s]
Loading safetensors checkpoint shards:  56% Completed | 5/9 [00:01<00:00,  4.47it/s]
Loading safetensors checkpoint shards:  67% Completed | 6/9 [00:01<00:00,  4.98it/s]
Loading safetensors checkpoint shards:  78% Completed | 7/9 [00:01<00:00,  4.85it/s]
Loading safetensors checkpoint shards:  89% Completed | 8/9 [00:01<00:00,  4.61it/s]
Loading safetensors checkpoint shards: 100% Completed | 9/9 [00:01<00:00,  4.47it/s]
Loading safetensors checkpoint shards: 100% Completed | 9/9 [00:01<00:00,  4.57it/s]

INFO 12-09 11:20:29 model_runner.py:1025] Loading model weights took 14.2487 GB
INFO LMCache: Initializing local-only (cpu) backend [2024-12-09 11:20:29,338] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/__init__.py:28
INFO LMCache: Using pinned cpu memory: False [2024-12-09 11:20:29,339] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/local_backend.py:56
DEBUG LMCache: Current storage backend type <class 'lmcache.storage_backend.local_backend.LMCLocalBackend'> [2024-12-09 11:20:29,339] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:35
INFO 12-09 11:20:36 gpu_executor.py:122] # GPU blocks: 2099, # CPU blocks: 4681
INFO 12-09 11:20:38 model_runner.py:1329] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 12-09 11:20:38 model_runner.py:1333] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 12-09 11:20:50 model_runner.py:1456] Graph capturing finished in 12 secs.
-------------- Pre-computing KV cache for the chunks -------------------
Processed prompts:   0%|                                                                                      | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]INFO LMCache: KV cache retrieving mode: RetrieveStatus.PREFILL [2024-12-09 11:20:50,497] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_injection.py:47
INFO LMCache: Using default batched implementation of the get() method [2024-12-09 11:20:50,498] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:108
INFO LMCache: Retrieved 0 chunks [2024-12-09 11:20:50,498] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:382
DEBUG LMCache: Returning the original input! [2024-12-09 11:20:50,498] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:640
INFO LMCache: KV cache saving mode: [<StoreStatus.PREFILL: 1>] [2024-12-09 11:20:50,638] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_injection.py:126
INFO LMCache: Using default batched implementation of the put() method [2024-12-09 11:20:50,656] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:85
INFO LMCache: Stored/updated 3 chunks, total time 0.00s, make chunks time 0.00s [2024-12-09 11:20:50,656] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:311
DEBUG LMCache: Store skips 0 tokens and then stores 648 tokens [2024-12-09 11:20:50,656] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:466
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.89it/s, est. speed input: 3172.65 toks/s, output: 4.90 toks/s]
Processed prompts:   0%|                                                                                      | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]INFO LMCache: KV cache retrieving mode: RetrieveStatus.PREFILL [2024-12-09 11:20:50,708] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_injection.py:47
INFO LMCache: Using default batched implementation of the get() method [2024-12-09 11:20:50,708] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:108
INFO LMCache: Retrieved 0 chunks [2024-12-09 11:20:50,708] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:382
DEBUG LMCache: Returning the original input! [2024-12-09 11:20:50,709] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:640
INFO LMCache: KV cache saving mode: [<StoreStatus.PREFILL: 1>] [2024-12-09 11:20:50,944] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_injection.py:126
INFO LMCache: Using default batched implementation of the put() method [2024-12-09 11:20:50,965] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:85
INFO LMCache: Stored/updated 5 chunks, total time 0.00s, make chunks time 0.00s [2024-12-09 11:20:50,965] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:311
DEBUG LMCache: Store skips 0 tokens and then stores 1213 tokens [2024-12-09 11:20:50,965] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:466
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53it/s, est. speed input: 3076.54 toks/s, output: 2.54 toks/s]
Running the real query here!
Processed prompts:   0%|                                                                                      | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]INFO LMCache: KV cache retrieving mode: RetrieveStatus.PREFILL [2024-12-09 11:20:51,110] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_injection.py:47
INFO LMCache: Using default batched implementation of the get() method [2024-12-09 11:20:51,111] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:108
INFO LMCache: Retrieved 0 chunks [2024-12-09 11:20:51,111] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:382
DEBUG LMCache: Returning the original input! [2024-12-09 11:20:51,111] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:640
INFO LMCache: KV cache saving mode: [<StoreStatus.PREFILL: 1>] [2024-12-09 11:20:51,493] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_injection.py:126
INFO LMCache: Using default batched implementation of the put() method [2024-12-09 11:20:51,523] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:85
INFO LMCache: Stored/updated 8 chunks, total time 0.00s, make chunks time 0.00s [2024-12-09 11:20:51,523] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:311
DEBUG LMCache: Store skips 0 tokens and then stores 1894 tokens [2024-12-09 11:20:51,524] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:466
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.17it/s, est. speed input: 2215.10 toks/s, output: 14.03 toks/s]
Newly generated text: ' This document mainly talks about ffmpeg, a video converter.'
DEBUG LMCache: Closing LMCache Engine [2024-12-09 11:20:51,963] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:229
INFO LMCache: Closed the put worker in local backend [2024-12-09 11:20:51,964] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/local_backend.py:208
```

**Comment by darren-qiu** [comment]
The above is the output log. You can see that `generate` after `precompute` is still `Retrieved 0 chunks
`
`INFO LMCache: Retrieved 0 chunks [2024-12-09 11:20:51,111] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:382
`

**Comment by ApostaC** [comment]
Hey @darren-qiu , we do have some code modifications in `vllm/model_executor/models/llama.py` (see https://github.com/LMCache/lmcache-vllm/blob/dev/lmcache_vllm/models/llama.py). So if Qwen uses a different model architecture than llama, it may not work. 

You can see what we changed in the `llama.py` by searching for the comment "# Injection for CacheBlend" in https://github.com/LMCache/lmcache-vllm/blob/dev/lmcache_vllm/models/llama.py

**Comment by EthanWuuu** [comment]
> Hey [@darren-qiu](https://github.com/darren-qiu) , we do have some code modifications in `vllm/model_executor/models/llama.py` (see https://github.com/LMCache/lmcache-vllm/blob/dev/lmcache_vllm/models/llama.py). So if Qwen uses a different model architecture than llama, it may not work.
> 
> You can see what we changed in the `llama.py` by searching for the comment "# Injection for CacheBlend" in https://github.com/LMCache/lmcache-vllm/blob/dev/lmcache_vllm/models/llama.py

hi @ApostaC ：
I have a few more questions regarding the cacheblend paper and its implementation.

1. Both the paper and the code use mistral-7B, and the demo with the code also uses mistral-7B. However, in lmcache-vllm, the model in cacheblend currently only has llama. Is there a chance that the code related to the mistral model will be open-sourced, or can the current version use cacheblend with mistral?
2. The paper and the code mention that different backends can be used. Is the ttft acceleration ratio in the paper(2.2-3.3x) based on 'cuda' or 'cpu'? Or is there any benchmark to compare the performance of different backends(cuda / cpu / disk / remote)?
3. Have you tested the performance of llama2-7b? How does it perform in terms of speed and quality.

Thanks. Anticipating your reply.

**Comment by ApostaC** [comment]
@EthanWuuu Hey, thanks for the questions.

1. Mistral-7B also uses llama models' backbone. So the open-sourced code directly supports llama 7b.
2. There is a benchmark script in the [benchmarks/rag](https://github.com/LMCache/LMCache/tree/dev/benchmarks/rag) folder. Feel free to try it out.
3. We do not have immediate numbers internally. Feel free to try it yourself. Happy to help if you meet any problems!
