### ISSUE TITLE
The size of tensor a (32) must match the size of tensor b (28) at non-singleton dimension 0

### ISSUE THREAD

**Issue by darren-qiu** [LMCache/LMCache#241]
When using Qwen2.5, this error will be reported. Is the qwen2.5 model not supported yet?
After looking at CacheGenConfig, the total number of layers is 32, but qwen2.5 only has 28 layers.

Please help me how to solve this problem

```
INFO LMCache: Using default batched implementation of the put() method [2024-11-25 20:40:13,368] -- /usr/local/lib/python3.11/site-packages/lmcache/storage_backend/abstract_backend.py:85
INFO LMCache: Stored/updated 1 chunks, total time 0.00s, make chunks time 0.00s [2024-11-25 20:40:13,369] -- /usr/local/lib/python3.11/site-packages/lmcache/cache_engine.py:311
DEBUG LMCache: Store skips 0 tokens and then stores 22 tokens [2024-11-25 20:40:13,369] -- /usr/local/lib/python3.11/site-packages/lmcache_vllm/vllm_adapter.py:466
INFO 11-25 20:40:13 metrics.py:351] Avg prompt throughput: 3.8 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%.
Exception in thread Thread-3 (put_worker):
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lmcache/storage_backend/remote_backend.py", line 69, in put_worker
    self.put_blocking(key, value)
  File "/usr/local/lib/python3.11/site-packages/lmcache/storage_backend/remote_backend.py", line 124, in put_blocking
    bs = self.serializer.to_bytes(kv_chunk)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lmcache/storage_backend/serde/serde.py", line 37, in to_bytes
    bs = self.s.to_bytes(t)
         ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lmcache/storage_backend/serde/cachegen_encoder.py", line 382, in to_bytes
    output_dict = encode_function(
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lmcache/storage_backend/serde/cachegen_encoder.py", line 282, in encode_function
    new_key, max_tensors_key = torch_quant_vectorized(key_bins, fp_k)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lmcache/storage_backend/serde/cachegen_encoder.py", line 57, in torch_quant_vectorized
    factor = MAX / max1  # shape [nlayers, ntokens, 1]
             ~~~~^~~~~~
RuntimeError: The size of tensor a (32) must match the size of tensor b (28) at non-singleton dimension 0
```

**Comment by YaoJiayi** [comment]
Cachegen hyperparameters are configured at https://github.com/LMCache/LMCache/blob/dev/lmcache/storage_backend/serde/cachegen_basics.py.

We can try to debug it asap. But feel free to create a PR to fix it!!

**Comment by darren-qiu** [comment]
Indeed, I set key_third_layers=28 and the problem was solved.

However, before I can further study the code, here are a few questions: What are the uses of the parameters here? Why is it set like this? Are there any benefits to this design?

**Comment by YaoJiayi** [comment]
Thanks for the bugfix! @darren-qiu  May I ask which line did you change?

They are cachegen hyper-parameters. For example, `start_layer=10, end_layer=32, bins=16` means we use 16 bins to perform arithmetic encoding between layer 10-32. Fewer bins might lead accuracy degradation. Larger bins will result in smaller compression ratio.

**Comment by darren-qiu** [comment]
Thanks for the explanation @YaoJiayi 

<img width="492" alt="image" src="https://github.com/user-attachments/assets/0a8f7fa8-3ea6-4923-b70d-ee099569b06d">

The red box is the code added for compatibility. The key is the line in the green box, set key_third_layers=28.

Yes, if these parameters are hyperparameters, then for qwen2.5, experiments are also needed to determine how to set these values.
