### ISSUE TITLE
fail to run python3 -c "import lmcache_vllm.vllm as vllm"

### ISSUE THREAD

**Issue by duyongtju** [LMCache/LMCache#246]
**Describe the bug**
I start a container with image lmcache_vllm:lmcache-0.1.3. when i execute next command, some error happend
```
 # python3 -c "import lmcache_vllm.vllm as vllm"
Using /root/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py310_cu121/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module torchac_backend...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lmcache_vllm.vllm'
```

I have tried different version, 0.1.0, 0.1.3 image, all the same error. Can any body hello? thank you so mush!

**To Reproduce**

```
docker run -itd --name lmcache --privileged --gpus all  --shm-size=128g lmcache_vllm:lmcache-0.1.3 bash
docker exec -it lmcache bash
python3 -c "import lmcache_vllm.vllm as vllm"
Using /root/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py310_cu121/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module torchac_backend...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lmcache_vllm.vllm'
```

**Comment by duyongtju** [comment]
![image](https://github.com/user-attachments/assets/0bb3bc59-98de-426a-96fa-d020e27a969f)

**Comment by YaoJiayi** [comment]
Hi, could you share the command you used to install LMCache?
