### ISSUE TITLE
Performance Regression: LMCache Slower than CacheBlend on TTFT with Same Dataset

### ISSUE THREAD

**Issue by xhx1022** [LMCache/LMCache#261]
**Describe the bug**  
In my tests comparing LMCache and CacheBlend on the same dataset, I found that LMCache performs slower in terms of TTFT (Time To First Token) compared to CacheBlend, even though both configurations use the same hardware (A100-80GB). This behavior is unexpected, and I'm trying to understand the cause of the performance drop with LMCache.

**To Reproduce**  
1. Set up LMCache with the configuration below and CacheBlend with default settings on the same machine (A100-80GB).
2. Use the "inputs" dataset from CacheBlend and run it with LMCache.
3. Compare the TTFT results between LMCache and CacheBlend.
4. Observe that TTFT on LMCache is generally slower than on CacheBlend.

**Expected behavior**  
I expected the performance (TTFT) of LMCache to be either the same as or faster than CacheBlend when using the same dataset and hardware setup.

**Desktop (please complete the following information):**  
- OS: [e.g. Ubuntu 22.04]  
- Browser: N/A  
- Version: N/A  

**Additional context**  
Here are the configuration details for LMCache I used:
```yaml
chunk_size: 256
local_device: "cuda"

# Enables KV blending
enable_blending: True

# Whether retrieve() is pipelined or not
pipelined_backend: True
```
Both LMCache and CacheBlend were tested on the same device (A100-80GB).
LMCache is expected to optimize KV retrieval with blending enabled, so it’s unclear why its TTFT is slower than CacheBlend’s.
Could you help identify why LMCache might be performing worse than CacheBlend under these conditions? Any insights would be appreciated.

**Comment by ApostaC** [comment]
Hey @xhx1022 , thanks for submitting the issue. By comparing to "CacheBlend", are you referring to this github repo https://github.com/YaoJiayi/CacheBlend?

**Comment by xhx1022** [comment]
> Hey @xhx1022 , thanks for submitting the issue. By comparing to "CacheBlend", are you referring to this github repo https://github.com/YaoJiayi/CacheBlend?

Hi @ApostaC , thanks for your response. Yes, I am referring to this repository: [CacheBlend](https://github.com/YaoJiayi/CacheBlend).

For example, when I replicated the `blend_musique.py` experiment, my code was as follows:

```python
import lmcache_vllm
import torch
from lmcache_vllm.blend_adapter import (append_separator,
                                        combine_input_prompt_chunks)
from lmcache_vllm.vllm import LLM, SamplingParams
import json
import numpy as np
from transformers import AutoTokenizer
from utils import load_dataset, normalize_question, build_qa_prompt, compute_f1
from pathlib import Path

eval_dataset = load_dataset("inputs/musique_s.json")

llm = LLM(model="/mnt/sdb/home/xhx/models/Mistral-7B-Instruct-v0.2", gpu_memory_utilization=0.8,
          #tokenizer=tokenizer,
          )
tokenizer = AutoTokenizer.from_pretrained("/mnt/sdb/home/xhx/models/Mistral-7B-Instruct-v0.2")
llm.set_tokenizer(tokenizer)

prefix_prompt = "You will be asked a question after reading several passages. Please directly answer the question based on the given passages. Do NOT repeat the question. The answer should be within 5 words..\nPassages:\n"
query_prompt = "\n\nAnswer the question directly based on the given passages. Do NOT repeat the question. The answer should be within 5 words. \nQuestion:"

ttft_blend = []
ttft_full = []
f1_blend = []
f1_full = []

def precompute_kv(text_chunk, llm):
    sampling_params_prefix = SamplingParams(temperature=0.0,
                                            max_tokens=1)
    text_chunk = append_separator(text_chunk)
    llm.generate([text_chunk], sampling_params_prefix)

i = 0 
for ex in eval_dataset:
    # if i == 20:
    #     break
    answers = ex["answers"]
    doc_prompts, q_prompt = build_qa_prompt(ex, query_prompt)

    print("-------------- Pre-computing KV cache for the chunks -------------------")
    # Concatenate old KVs
    for chunk in doc_prompts:
        precompute_kv(chunk, llm)

    print("Running the real query here!")
    sampling_params = SamplingParams(temperature=0, max_tokens=32)
    user_prompt = [prefix_prompt]
    user_prompt.extend(doc_prompts)
    user_prompt.append(q_prompt)
    user_prompt = combine_input_prompt_chunks(user_prompt)
    output = llm.generate(user_prompt, sampling_params)
    res = output[0].outputs[0].text
    print(f"Cached generation: {res}")
    ttft = output[0].metrics.first_token_time-output[0].metrics.first_scheduled_time
    print(f"TTFT with cache: {ttft}")
    ttft_blend.append(ttft)
    f1 = max([compute_f1(res, answer, tokenizer) for answer in answers])
    f1_blend.append(f1)
    i += 1


print("---------------Result Summary---------------------")
print(f"TTFT with cache: {np.mean(ttft_blend)}")
print(f"F1 with cache: {np.mean(f1_blend)}")

# Graceful exit
lmcache_vllm.close_lmcache_engine()
```
the config is
```yaml
chunk_size: 256
local_device: "cuda"

# Enables KV blending
enable_blending: True

# Whether retrieve() is pipelined or not
pipelined_backend: False
```

Due to the large dataset causing errors, I set the number of iterations to 20.
Here are the results:
```
# ---------------Result Summary---------------------
# TTFT with cache: 0.1629036545753479
# F1 with cache: 0.3101577302158697
```
However, the results from CacheBlend are as follows:
```
# ---------------Result Summary---------------------
# k = 20
# TTFT with cache: 0.12906403541564943
# TTFT with full prefill: 0.5165045738220215
# F1 with cache: 0.4249595543345544
# F1 with full prefill: 0.37796288798920374
```

**Comment by xhx1022** [comment]
Similarly, when I used LMCache to reproduce the code from [blend.py](https://github.com/YaoJiayi/CacheBlend/blob/main/example/blend.py), the same error occurred:

```plaintext
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/worker/model_runner_base.py", line 112, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 114, in new_execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/model_executor/models/llama.py", line 448, in forward
[rank0]:     model_output = self.model(input_ids, positions, kv_caches,
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/lmcache-vllm/lmcache_vllm/models/llama.py", line 196, in llama_model_forward_with_blend
[rank0]:     hidden_states, residual = layer(
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/lmcache-vllm/lmcache_vllm/models/llama.py", line 151, in llama_decoder_layer_forward_with_blend
[rank0]:     hidden_states = self.self_attn(
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/lmcache-vllm/lmcache_vllm/models/llama.py", line 124, in llama_attn_forward_with_blend
[rank0]:     q, k, v, attn_metadata = do_blend(
[rank0]:   File "/mnt/sdb/home/xhx/projects/lmcache-vllm/lmcache_vllm/blend_adapter.py", line 290, in do_blend
[rank0]:     blender_output = blend_metadata.blend_executor.blend(
[rank0]:   File "/mnt/sdb/home/xhx/projects/LMCache/lmcache/blend/executor.py", line 195, in blend
[rank0]:     original_positions.to(device=retrieved_k.device,
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/sdb/home/xhx/projects/LMCache/LMCache_examples/blend.py", line 42, in <module>
[rank0]:     output = llm.generate(user_prompt, sampling_params)
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/utils.py", line 1036, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/entrypoints/llm.py", line 348, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/entrypoints/llm.py", line 715, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/engine/llm_engine.py", line 1223, in step
[rank0]:     outputs = self.model_executor.execute_model(
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/executor/gpu_executor.py", line 130, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/worker/worker_base.py", line 327, in execute_model
[rank0]:     output = self.model_runner.execute_model(
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/mnt/sdb/home/xhx/projects/vllm/vllm/worker/model_runner_base.py", line 125, in _wrapper
[rank0]:     pickle.dump(dumped_inputs, filep)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/storage.py", line 1006, in __reduce__
[rank0]:     torch.save(self, b, _use_new_zipfile_serialization=False)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/serialization.py", line 656, in save
[rank0]:     _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
[rank0]:   File "/home/xhx/softwares/miniconda3/envs/lmcache/lib/python3.10/site-packages/torch/serialization.py", line 800, in _legacy_save
[rank0]:     storage._write_file(f, _should_read_directly(f), True, torch._utils._element_size(dtype))
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Here is my code
```python
import lmcache_vllm
import torch
from lmcache_vllm.blend_adapter import (append_separator,
                                        combine_input_prompt_chunks)
from lmcache_vllm.vllm import LLM, SamplingParams
import json
import time
from transformers import AutoTokenizer
torch.multiprocessing.set_start_method('spawn')

def precompute_kv(text_chunk, llm):
    sampling_params_prefix = SamplingParams(temperature=0.0,
                                            top_p=0.95,
                                            max_tokens=1)
    text_chunk = append_separator(text_chunk)
    llm.generate([text_chunk], sampling_params_prefix)

llm = LLM(model="/mnt/sdb/home/xhx/models/Mistral-7B-Instruct-v0.2", gpu_memory_utilization=0.9,
          #tokenizer=tokenizer,
          )
tokenizer = AutoTokenizer.from_pretrained("/mnt/sdb/home/xhx/models/Mistral-7B-Instruct-v0.2")
llm.set_tokenizer(tokenizer)

#TODO (Jiayi): fix last len


for sample_idx in range(1,2):
    f = open(f"inputs/{sample_idx}.json")
    ex = json.load(f)
    chunk_num = ex['chunk_num']
    q_prompt = ex['query']
    print("-------------- Pre-computing KV cache for the chunks -------------------")
    # Concatenate old KVs
    doc_prompts = [ex[f'{i}'] for i in range(chunk_num)]
    for doc in doc_prompts:
        precompute_kv(doc, llm)

 
    doc_prompts.append(q_prompt)
    user_prompt = combine_input_prompt_chunks(doc_prompts)
    sampling_params = SamplingParams(temperature=0, max_tokens=10)
    output = llm.generate(user_prompt, sampling_params)
    print(f"Cached generation: {output[0].outputs[0].text}")
    print(f"TTFT with cache: {output[0].metrics.first_token_time-output[0].metrics.first_scheduled_time}")
```

**Comment by ApostaC** [comment]
Hey @xhx1022 , we are going to release a new version soon (today or tomorrow), and the new version contains some performance optimization. 

Can you try it again after the new version is released?

**Comment by xhx1022** [comment]
> Hey @xhx1022 , we are going to release a new version soon (today or tomorrow), and the new version contains some performance optimization.
> 
> Can you try it again after the new version is released?

Ok, looking forward to your update!

**Comment by Hanchenli** [comment]
@xhx1022 Does the problem still persist? If not I will close this issue.
