### ISSUE TITLE
Error when serving with blending

### ISSUE THREAD

**Issue by jokmingwong** [LMCache/LMCache#290]
## Problems
I encountered the following issues while testing server performance after using Blend on L20. The models I tested include Mistral-7B-Instruct-v0.2 and Qwen-2-7B-Instruct, both of which exhibited the same problems. The dataset used for testing was ShareGPT, and similar issues were observed with other datasets as well. The problems occurred when the request rate was limited to 1.

## Test environments
```
Hardware: Nvidia Ada L20
cuda == 12.1
torch version == 2.4.0+cu121
python version == 3.11.6
lmcache==0.1.4
lmcache_vllm == 0.6.2.2
```

## Commands
On server side:
```bash
LMCACHE_CONFIG_FILE=cpu_local.yaml lmcache_vllm serve Mistral-7B-Instruct-v0.2  --gpu-memory-utilization 0.9  --enable-prefix-caching --served-model-name aa
```
On client side:
The file benchmark_serving.py is sourced from the [vllm benchmarks repository](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py).
```bash
python3 benchmark_serving.py --model aa --dataset-name sharegpt --tokenizer Mistral-7B-Instruct-v0.2/ --dataset-path /ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 100 --request-rate 1
```
The cpu_local.yaml is
```yaml
chunk_size: 256
local_device: "cpu"

# Enables KV blending
enable_blending: True

# Whether retrieve() is pipelined or not
pipelined_backend: False
```

## Problem logs
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 257, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 253, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 230, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/usr/lib64/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f1a50ec6a50

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 253, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 242, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/entrypoints/openai/serving_completion.py", line 248, in completion_stream_generator
    |     async for prompt_idx, res in result_generator:
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/utils.py", line 490, in merge_async_iterators
    |     item = await d
    |            ^^^^^^^
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 486, in _process_request
    |     raise request_output
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 486, in _process_request
    |     raise request_output
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 486, in _process_request
    |     raise request_output
    | AssertionError
    +------------------------------------
CRITICAL 12-31 17:35:14 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:55778 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2259859]
[rank0]: Traceback (most recent call last):
[rank0]:   File "<string>", line 1, in <module>
[rank0]:   File "/usr/lib64/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
[rank0]:     exitcode = _main(fd, parent_sentinel)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib64/python3.11/multiprocessing/spawn.py", line 135, in _main
[rank0]:     return self._bootstrap(parent_sentinel)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib64/python3.11/multiprocessing/process.py", line 332, in _bootstrap
[rank0]:     threading._shutdown()
[rank0]:   File "/usr/lib64/python3.11/threading.py", line 1581, in _shutdown
[rank0]:     lock.acquire()
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 384, in signal_handler
[rank0]:     raise KeyboardInterrupt("MQLLMEngine terminated")
[rank0]: KeyboardInterrupt: MQLLMEngine terminated
```
## Question
Could it be that there are still issues with server-side support for the Blend feature? What modifications are needed to address this? Thanks for response.

**Comment by jokmingwong** [comment]
Additional testing results: When I reduce `max-num-seqs`, the maximum batch size, or lower `gpu-memory-utilization` on server side, the number of successfully processed requests increases.

**Successful requests:** 
from **0** -----set max-num-seqs=1 ---> **11**  -----lower gpu_memory_utilization=0.5 ----> **43**

**Comment by ApostaC** [comment]
@jokmingwong , thanks for submitting the issue to LMCache project. Can you give more details about the `benchmark_serving.py` to help us better reproduce the problem?
Also, since LMCache needs some GPU buffer to offload the KV cache, it's better to set a lower `gpu-memory-utilization` (e.g., 0.7).

@XbzOnGit Can you take a look at this when available?

**Comment by XbzOnGit** [comment]
Hi @jokmingwong , try you try [LMCache PR 285](https://github.com/LMCache/LMCache/pull/285) and [lmcache-vllm PR 45](https://github.com/LMCache/lmcache-vllm/pull/45), with 
```
LMCACHE_CONFIG_FILE=cpu_local.yaml python3 -m lmcache_vllm.vllm.entrypoints.openai.api_server --model Mistral-7B-Instruct-v0.2  --gpu-memory-utilization 0.7
```
?
(You can git clone [repo1](https://github.com/XbzOnGit/LMCache) and [repo2](https://github.com/XbzOnGit/lmcache-vllm), run git checkout local-dev/fix-blend-retrieve and pip install -e ./ in both of them)
This one lowers 0.9 to 0.7 and removes prefix cache of vllm.
And the PRs above fixed some known bugs.

**Comment by XbzOnGit** [comment]
Hi @jokmingwong, we have merged some fixes on CacheBlend.
Now you can simply try this and check if it works. Note that precompute needs some changes. Please check examples/blend_kv/online_kv.py  
```
LMCACHE_CONFIG_FILE=cpu_local.yaml python3 -m lmcache_vllm.vllm.entrypoints.openai.api_server --model Mistral-7B-Instruct-v0.2  --gpu-memory-utilization 0.7
```
Feel free to report again if still problems. It would be helpful if you can share benchmark_serving.py so that we can reproduce it.

**Comment by jokmingwong** [comment]
@XbzOnGit @ApostaC  Thanks for reply!
The issue persists even after using the latest lmcache and lmcache_vllm installed with pip install -e, and reducing gpu-memory-utilization to 0.7 or even lower.

The file `benchmark_serving.py` is sourced from the [vllm benchmarks repository](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py).

On server side:
```bash
LMCACHE_CONFIG_FILE=cpu_local.yaml python3 -m lmcache_vllm.vllm.entrypoints.openai.api_server --model ./Mistral-7B-Instruct-v0.2/ --gpu-memory-utilization 0.7 --served-model-name aa
```
And on client side:
```bash
python3 benchmark_serving.py --model aa --dataset-name sharegpt --tokenizer Mistral-7B-Instruct-v0.2/ --dataset-path ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 5
```
<details>
<summary> The ERROR logs </summary>
ERROR 01-06 11:06:39 engine.py:157] AssertionError()
ERROR 01-06 11:06:39 engine.py:157] Traceback (most recent call last):
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 155, in start
ERROR 01-06 11:06:39 engine.py:157]     self.run_engine_loop()
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 218, in run_engine_loop
ERROR 01-06 11:06:39 engine.py:157]     request_outputs = self.engine_step()
ERROR 01-06 11:06:39 engine.py:157]                       ^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 236, in engine_step
ERROR 01-06 11:06:39 engine.py:157]     raise e
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 227, in engine_step
ERROR 01-06 11:06:39 engine.py:157]     return self.engine.step()
ERROR 01-06 11:06:39 engine.py:157]            ^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/llm_engine.py", line 1264, in step
ERROR 01-06 11:06:39 engine.py:157]     outputs = self.model_executor.execute_model(
ERROR 01-06 11:06:39 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/executor/gpu_executor.py", line 130, in execute_model
ERROR 01-06 11:06:39 engine.py:157]     output = self.driver_worker.execute_model(execute_model_req)
ERROR 01-06 11:06:39 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/worker_base.py", line 303, in execute_model
ERROR 01-06 11:06:39 engine.py:157]     inputs = self.prepare_input(execute_model_req)
ERROR 01-06 11:06:39 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/worker_base.py", line 291, in prepare_input
ERROR 01-06 11:06:39 engine.py:157]     return self._get_driver_input_and_broadcast(execute_model_req)
ERROR 01-06 11:06:39 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/worker_base.py", line 253, in _get_driver_input_and_broadcast
ERROR 01-06 11:06:39 engine.py:157]     self.model_runner.prepare_model_input(
ERROR 01-06 11:06:39 engine.py:157]   File "lmcache/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 425, in wrap_prepare_model_input
ERROR 01-06 11:06:39 engine.py:157]     model_input = original_prepare_model_input(
ERROR 01-06 11:06:39 engine.py:157]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/model_runner.py", line 1519, in prepare_model_input
ERROR 01-06 11:06:39 engine.py:157]     model_input = self._prepare_model_input_tensors(
ERROR 01-06 11:06:39 engine.py:157]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157]   File "lmcache/lmcache-vllm/lmcache_vllm/vllm_injection.py", line 444, in wrap_prepare_model_input_tensors
ERROR 01-06 11:06:39 engine.py:157]     attach_blend_prompt_indices(seq_group_metadata_list, attn_metadata)
ERROR 01-06 11:06:39 engine.py:157]   File "lmcache/lmcache-vllm/lmcache_vllm/blend_adapter.py", line 313, in attach_blend_prompt_indices
ERROR 01-06 11:06:39 engine.py:157]     assert seq_data_idx == len(seq_lens)
ERROR 01-06 11:06:39 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-06 11:06:39 engine.py:157] AssertionError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 257, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 253, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 230, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/usr/lib64/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f0dd3474dd0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 253, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 242, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/entrypoints/openai/serving_completion.py", line 248, in completion_stream_generator
    |     async for prompt_idx, res in result_generator:
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/utils.py", line 490, in merge_async_iterators
    |     item = await d
    |            ^^^^^^^
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 486, in _process_request
    |     raise request_output
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 486, in _process_request
    |     raise request_output
    |   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/multiprocessing/client.py", line 486, in _process_request
    |     raise request_output
    |   [Previous line repeated 2 more times]
    | AssertionError
    +------------------------------------
</details>

**Comment by jokmingwong** [comment]
Additional information:
I resolved this issue by using `examples/blend_kv/online_kv.py` (serial Q&A and batch_size = 1) or setting `--max-num-seqs`=1 or 2 when starting the vllm openai service. I suspect this is caused by thread conflicts that occur when the Blend feature handles multiple requests in one batch. When I set `--max-num-seqs` >= 3, the errors occured like above mentioned.

**Comment by XbzOnGit** [comment]
> Additional information: I resolved this issue by using `examples/blend_kv/online_kv.py` (serial Q&A and batch_size = 1) or setting `--max-num-seqs`=1 or 2 when starting the vllm openai service. I suspect this is caused by thread conflicts that occur when the Blend feature handles multiple requests in one batch. When I set `--max-num-seqs` >= 3, the errors occured like above mentioned.

Thanks for this information. It's a problem with cuda graph paddings. We are fixing this soon.

**Comment by XbzOnGit** [comment]
@jokmingwong  Could you check this [PR](https://github.com/LMCache/lmcache-vllm/pull/50) of lmcache-vllm?
You can manually change this one line of code and benchmark again before we merge it.

**Comment by jokmingwong** [comment]
@XbzOnGit Thank you for your reply. This [PR](https://github.com/LMCache/lmcache-vllm/pull/50) has resolved the issue, so I will close this issue. However, it seems that GPU memory usage is higher compared to the vLLM baseline, which might be potential direction for optimization🤔.
